### ISSUE TITLE
automatic update of cran.toc.rds

### ISSUE THREAD

**Issue by urisohn** [groundhogR/groundhogR#53]
when calling groundhog.librar() past the most recen date in cran.toc.rds the file is not updated, instead it says date is not available.

**Comment by urisohn** [comment]
ok having done some testing, i think the culprit is set.groundhog.folder()
I think it shuold do two things it does not currently do
1) Download the cran.toc.rds et al files to it when set
2) Verify they could be written, and if not, give a warning to users they have chosen a folder that R does not have rights to

**Comment by Bisaloo** [comment]
I think https://github.com/groundhogR/groundhogR/commit/105867c8231a52d18fd96ebd19360bd94d9eafba should fix this

**Comment by urisohn** [comment]
I had written a comment here that acted up (showed up multiple time) now missing, so just in case.

Just tried it, it does not fix it. I think the problem is permissions.
We don't check that teh folder the user sets is one R has rights to save to. 
Turns out, in Windows it probably is only the USERS/ folder

So we have to chagne the message not to recommend dropbox.
We should check there is permissions to write in it
I do think the easiest way is ot just force a redownload of cran.toc.rds when the folder is set, and verifying it got downloaded, Perhaps starting with teh smaller of the three, mran.missing.dates, so that it will fail faster if it has to

**Comment by urisohn** [comment]
I am hesitant to make this change myself because i dont understand the interaction with the package environment all that well.
But seems like a related issue is that
set.groundhog.folder("") does not just undo the previous decision and return to default, but sets the path to nothing and requires running get.groundhog.folder(), i think it would make sense to include that call whenever the patch is empty or the pat does not have writing writes over.

but i still don't undesrtand where cran.toc.rds is read from when the folder set as the defaut does not exist

**Comment by Bisaloo** [comment]
I think I got it right this time. It fixes it on my computer. Could you try again please?

**Comment by urisohn** [comment]
seems to be working

**Comment by Bisaloo** [comment]
For future reference, fixed by https://github.com/groundhogR/groundhogR/commit/6fe68c9bff8718281c84a4d09d28ae4a8e75454d

**Comment by urisohn** [comment]
and did you do anything with permissions?

**Comment by Bisaloo** [comment]
No, I think this was just a red herring.

If the path is empty, it will just prompt you to put a non-empty path and you will not be able to continue until you do so.

Beyond that, I'm not really knowledgeable about windows but I'm quite confident R has the same permissions as the user running it. Otherwise, you wouldn't be able to open e.g. a csv file in your dropbox, which would surely be a problem for many other people outside of groundhog.

Now, I can always add a check to see if the user has a permission to write in the folder (in case someone sets it in the system folder of windows, where you require special permissions but this a really unlikely mistake. And someone who does this knowingly will know how to change this) but base R functions will take care of this and the wording is quite explicit. The error you saw about wrong dates did not have anything to do with this.
